VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Floss Integrations and Securities LLC"
ORG_URL = "https://doaflo55.github.io"
ORG_LOGO = "https://doaflo55.github.io/1781608075958~2.png"
ORG_DESCRIPTION = "A High-Value Correcting and Holding Exchange, Self Custody Anchored digital asset integration securities services for the Stellar ecosystem with Expansive Automatic Protocals for Conversions and the Decentralization Utility "
ORG_PHYSICAL_ADDRESS = "SC, United States"
ORG_OFFICIAL_EMAIL = "contact@doaflo55.github.io"
ORG_SUPPORT_EMAIL = "contact@doaflo55.github.io"

[[PRINCIPALS]]
name = "Doa Floss"
email = "contact@doaflo55.github.io"

[[CURRENCIES]]
code = "USDJBTC"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "USDJBTC TOKEN"
desc = "PLINK Protocol designation: Foundation/Identifying (BTC-Anchor)."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "USDJSOL"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "USDJSOL TOKEN"
desc = "PLINK Protocol designation: Yield/Staking Engine."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "rwaXMR"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "RwA XMR TOKEN"
desc = "PLINK Protocol designation: Yielding Engine Pool."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "eXCH"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "EXPANDED XCH TOKEN"
desc = "PLINK Protocol designation: Mining-Farming Rewards Pool."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "BTCXD"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "BTCXD TOKEN"
desc = "The Laughing Bitcoin: A memed asset now pooling on Stellar."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "MOGLMN"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "MOGLMN TOKEN"
desc = "Protocol designation: MOG Lumens integration."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "OPLZ"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "OPLZ TOKEN"
desc = "PLYNK Protocol designation: Wrapped MOGLMN/Optimism parity."
is_asset_anchored = false
status = "live"
