VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Floss Integrations and Securities LLC"
ORG_URL = "https://doaflo55.github.io"
ORG_LOGO = "https://doaflo55.github.io/1781608075958~2.png"
ORG_DESCRIPTION = "A High-Value Correcting and Holding Exchange, Self Custody Anchored digital asset integration securities services for the Stellar ecosystem with Expansive Automatic Protocals for Conversions and the Decentralization Utility "
ORG_PHYSICAL_ADDRESS = "SC, United States"
ORG_OFFICIAL_EMAIL = "contact@doaflo55.github.io"
ORG_SUPPORT_EMAIL = "contact@doaflo55.github.io"

[[PRINCIPALS]]
name = "Doa Floss"
email = "contact@doaflo55.github.io"

[[CURRENCIES]]
code = "USDJBTC"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "USDJBTC"
desc = "This token specifically serves as a foundational digital anchor for the USG providing stable and secure Bitcoin Backed synthetic liquidity from the amount held in the SBR (Strategic Bitcoin Reserve)  It is engineered to facilitate reliable and identifiable real world value for institutional-grade participants, ensuring that your digital holdings remain integrated within a transparent, high-performance financial framework designed for modern asset management."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "USDJSOL"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "USDJSOL"
desc = "Our primary yield and staking engine, this asset is optimized to distribute liquidity efficiently and annually. It allows participants to engage in high-speed, secure wrapped/staking and pooling/swapping activities, fostering growth and long-term participation while maintaining the integrity and robust settlement speeds that the Stellar network is globally renowned for providing. AYP 7%."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "rwaXMR"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "RwaXMR"
desc = "This token functions as an advanced real-world integration asset. It is specifically designed to bridge privacy-adjacent digital assets with open blockchain ledgers by leveraging recycled commodities like silver and copper for advanced financial utility while benefiting from our rigorous security standards and audited institutional infrastructure."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "eXCH"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "eXCH"
desc = "Designed as the central utility for our farming ecosystem, this token facilitates the fair and transparent distribution of rewards to all active network participants. It powers our operational incentive structures, ensuring that contributors are properly recognized within a stable, high-performance environment built for scale and sustainability at a very low cost."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "BTCXD"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "BTCXD"
desc = "This asset represents a unique, community-centric digital store of value. THE LAUGHING BITCOIN is leveraging the high-speed settlement capabilities of the Stellar network, it transforms traditional meme assets into a functional pooling mechanism that provides efficient, low-latency transaction processing for a globally distributed and highly active user base."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "MOGLMN"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "MOGLMN"
desc = "This token is the cornerstone of achievement. seamless interoperability between independent direct and efficient cross-protocol platforms, this MOG/LUMEN ensures that your assets move fluidly through the network, supported by our holding standards and a commitment to the communities of digital exchanges."
is_asset_anchored = false
status = "live"

[[CURRENCIES]]
code = "OPLZ"
issuer = "GBXI6T3CIKBTGRJZQHSNSP2GLIQ7EOGOPXPJEQULVI4MOCMVSGGNP4FU"
display_decimals = 7
name = "OPLZ"
desc = "Stellar Optimisim. A wrapped and expanded asset, this token ensures perfect synchronization between diverse chain networks & pools. It provides the necessary infrastructure to maintain cross-chain stability and compatibility, offering users a reliable gateway to optimize their asset performance through a well-governed and highly secure digital framework for decentralized commerce."
is_asset_anchored = false
status = "live"
